name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Simulate a Build
        run: echo 'hello youtube' > output.txt
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:          
          name: 'your-artifact-name'
          path: 'output.txt'
          
      - name: Create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Simple test issue
          body: my new issue