name: Deploy Using Environment

on:
  workflow_run:
    workflows: [CI]
    branches: [master, main]
    types:
        - completed

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'https://www.google.com'

    steps:
      - name: Deploy to PROD
        run: echo Simulating Deployment
